---
services:
  cb:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "${CB_PORT}:8978"
    volumes:
      - cb-data:/opt/cloudbeaver/workspace

  ch:
    image: clickhouse/clickhouse-server:latest
    ports:
      - ${CH_HTTP_PORT}:8123
      - ${CH_TCP_PORT}:9000
    env_file:
      - path: .env
      - path: .env.local
        required: false
    volumes:
      - ch-data:/var/lib/clickhouse/
      - ch-logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  ddb:
    image: amazon/dynamodb-local
    ports:
      - "${DDB_PORT}:8000"
    env_file:
      - path: .env
      - path: .env.local
        required: false
    volumes:
      - ddb-data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  mysql:
    image: mysql:8
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - path: .env
      - path: .env.local
        required: false
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["mysqld", "--mysql-native-password=ON"]

  pg:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - path: .env
      - path: .env.local
        required: false
    volumes:
      - pg-data:/var/lib/postgresql/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - path: .env
      - path: .env.local
        required: false
    depends_on:
      - pg
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  cb-data:
  ch-data:
  ch-logs:
  ddb-data:
  mysql-data:
  pg-data:
  pgadmin-data:
  redis-data:
